### THIS IS ONLY A PARTIAL CONFIGURATION FILE. 
### JUST ADD THESE PARTS TO YOUR configuration.yaml
mqtt:
  broker: your.mqtt.HA.pi
  port: 1883
  client_id: home-assistant-1
  username: yourmqttname
  password: yourmqttpw

#######################################
############## Holiday Outside Lights ######
#######################################

light:
  - platform: mqtt
    name: "Holiday Lights"
    command_topic: "bruh/mqttstrip/setpower"
    state_topic: "bruh/mqttstrip/setpowerpub"
    rgb_state_topic: "bruh/mqttstrip/setcolorpub"
    rgb_command_topic: "bruh/mqttstrip/setcolor"
    brightness_state_topic: "bruh/mqttstrip/setbrightnesspub"
    brightness_command_topic: "bruh/mqttstrip/setbrightness"
    optimistic: false

input_select:
  holiday_led_effect:
    name: Holiday LED Effect
    options:
     - "Christmas"
     - "Candy Cane"
     - "Holly Jolly"
     - "Valentine"
     - "Lovey Day"
     - "St Patty"
     - "Easter"
     - "USA"
     - "Independence"
     - "Go Blue"
     - "Hail"
     - "Touchdown"
     - "Halloween"
     - "Punkin"
     - "Thanksgiving"
     - "Turkey Day"
     - "BPM"
     - "Confetti"
     - "Cyclon Rainbow"
     - "Dots"
     - "Fire"
     - "Glitter"
     - "Juggle"
     - "Lightning"
     - "Police All"
     - "Police One"
     - "Rainbow"
     - "Rainbow with Glitter"
     - "Ripple"
     - "Sinelon"
     - "Solid"
     - "Twinkle"
    initial: "Solid"

input_number:
  animation_speed:
    name: Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

automation: 
  - alias: "Holiday Input Effect"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_select.holiday_led_effect
    action:
      - service: mqtt.publish
        data_template:
          topic: "bruh/mqttstrip/seteffect"
          payload: '{{ trigger.to_state.state | string }}'

  - alias: "Animation Speed"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_number.animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "bruh/mqttstrip/setanimationspeed"
          payload: '{{ trigger.to_state.state | int }}'
################################
